UIFC-373: Filters SASQ does not remember search query
folio-org/ui-finc-select pull request #292
Opened 2024-08-29 14:01 UTC by elsenhans

https://folio-org.atlassian.net/browse/UIFC-373

2024-08-30 16:45 UTC, alb3rtino requested changes
The problem here is, that when no search string is provided `storedSearchString` becomes `{}` and this is not what `initialSearchState` expects.

To fix the problem, I suggest changing 
```javascript
initialSearchState={storedSearchString}
```
to
```javascript
initialSearchState={{ query: storedSearchString.query }}
```

`MetadataSources` and `MetadataCollections` components are handling this in the `getCombinedSearch()` function.

2024-09-02 07:01 UTC, elsenhans commented
@alb3rtino thanks for the hint!

2024-09-02 07:23 UTC, alb3rtino requested changes

2024-09-02 07:23 UTC, alb3rtino commented on src/components/Filters/Filters.js
> +  const [storedSearchString, setStoredSearchString] = useState(localStorage.getItem('fincSelectFilterSearchString') ? JSON.parse(localStorage.getItem('fincSelectFilterSearchString')) : defaultSearchS
And can we please not reformat any code that had no changes made to it?
This will help keep PRs more readable.
Thanks!

2024-09-02 07:39 UTC, alb3rtino approved these changes

2024-09-02 07:48 UTC, merged